### PR TITLE
Adding support for Audit and Issue; namespace renaming for compliance

### LINKED ISSUE #38: Adding support for iAudit objects
#### Description:

As discussed with @enarhi

### LINKED ISSUE #41: 3DRepo_oM: Namespace update from `External` to `Adapters`
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.TDRepo` or `BH.Engine.Adapters.TDRepo` instead of `BH.oM.External`, etc.

The Adapter namespace should remain at `BH.Adapter.TDRepo` instead of `BH.Adapter.External.TDRepo`.

**ALSO make sure that the default namespace is set correctly in the oM and Engine Project properties.**
➡️ [Right click on the project, navigate to the Application tab, and check the default namespace](https://user-images.githubusercontent.com/6352844/90246499-b122da00-de2c-11ea-92c0-edf0fcf81584.png).

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/958
   
### Issues addressed by this PR

Closes #38
Closes #41

### Test files

In the folder `Buildings and Habitats object Model - 12_Scripts\01_Test Scripts\3DRepo_Toolkit`
https://burohappold.sharepoint.com/:f:/s/BHoM/EuDLmS6DhKxIjcW1KvQhcUsBimTlUPUWli5ENwVN6yy86A?e=hVnzeT

### Changelog

- Adding Push and Pull of `oM.Inspection.Issue`s.
- Namespace renaming to `Adapters` for compliance.

### CODE REVIEW

**Review by enarhi — DISMISSED** [review]
LGTM. General functionality working as expected, Issues regarding specific description and resource bugs have been logged as separate issues.

**Comment by enarhi** [comment]
Moved to #47

**Comment by alelom** [comment]
@enarhi what is the specific reason we had to move this to #47? I'd just like to avoid losing the Commit history if possible.

**Comment by enarhi** [comment]
The branch can not be rebased due to the conflicts so we were going to copy to a new branch and merge. The rebase issue appears to be from the namespace change occurring on commits in this branch and already committed to master. Now that we have time on this one I have reopened this pr so you can resolve the merge conflicts as needed and then we can get it merged up.

**Review by enarhi — APPROVED** [review]
LGTM

**Pull request merged**
