### PR TITLE
Removed Rhino dependency; align to new Build events

### LINKED ISSUE #31: Remove dependencies on Rhinocommon/Rhinoceros_Toolkit
#### Broken rules:

Currently, 3DRepo needs to depend on both Rhinocommon/Rhinoceros_Toolkit because of the MeshRepresentation things.

#### Suggestions to restore compliance:

Once the MeshRepresentation is taken care of appropriately in the base Engine, a refactor needs to happen and these dependencies removed.

### LINKED ISSUE #37: Align to Build events (copy to ProgramData)
#### Broken rules:

As title

#### Suggestions to restore compliance:

Add build event
`xcopy "$(TargetDir)$(TargetFileName)"  "C:\ProgramData\BHoM\Assemblies" /Y`

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/839
https://github.com/BHoM/TriangleNet_Toolkit/pull/27
   
### Issues addressed by this PR

Closes #31 
Closes #37 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EsCg_tyvF7ZBr0P_CbVV1jgBJu0GvbIbdvIUK5VHzOiK4A?e=5E1Yem

image

### CODE REVIEW

**Comment by al-fisher** [comment]
Hey @alelom - have updated the CI dependances and is working now!

**Comment by alelom** [comment]
@al-fisher same as https://github.com/BHoM/BHoM_Engine/pull/1900#issuecomment-667884260

**Comment by alelom** [comment]
Created issue for the failing Push https://github.com/BHoM/3DRepo_Toolkit/issues/39 @al-fisher

**Review by al-fisher — DISMISSED** [review]
Happy to approve based on the scope of this PR and the new issue being raised for unrelated uncovered bug
Approving to unblock

**Comment by alelom** [comment]
Thanks @al-fisher ! Could you please also merge as I don't have auth to do it?

**Comment by al-fisher** [comment]
@alelom afraid cannot merge yest as this branch cannot be rebased due to conflicts

**Comment by alelom** [comment]
Replaced by https://github.com/BHoM/3DRepo_Toolkit/pull/40

**Pull request closed without merging**
