### PR TITLE
Enable Custom Representation Mesh

### LINKED ISSUE #33: Allow custom representation mesh to be used
#### Description:

If a "CustomRepresentation" is found (for now, in the CustomData), then use it instead of calculating a MeshRepresentation for the object.

This enables any mesh to be used as a representation for the object, for example the ones pulled from Revit: https://github.com/BHoM/Revit_Toolkit/pull/686

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/839
   
### Issues addressed by this PR

Closes #33

### CODE REVIEW

**Comment by al-fisher** [comment]
Thanks @alelom 
Pushing the Physical objects seems to be working similar to your demo. Which is good.

Pushing a `ModelInstance` from Revit is not however not working for me - saved a test script in folder [in folder with the others](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2F3DRepo%5FToolkit%2F%2334%2DCustomMesh&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) with internalised single` ModelInstance` for testing

**Comment by alelom** [comment]
> ModelInstance

Testing that now.

**Comment by alelom** [comment]
~~I do not really know what `ModelInstance` is...~~ I now see what you mean, there is a geometry there in customData. Working on that now.

<details>
...but by the looks of it it seems to be comparable to a CustomObject. The problem is, unlike Speckle, 3DRepo only reasons in terms of meshes, and object whose mesh representation can be computed can be then pushed to it.

I propose to tackle this problem separately in another PR. To solve it, we might simply create a Mesh container – e.g. a tiny one-faced mesh, centered in the origin – that will be the container for all of the BHoM objects that do not have a representation yet. This means to build "Speckle behaviour" into 3DRepo ourselves.
</details>

**Comment by alelom** [comment]
@al-fisher the problem seems to be the size of the mesh pulled from Revit for that chair:
image

The 3DRepo hangs in writing that, then it cancels the request because it's too big:
image

which is what it's supposed to do with meshes of this entity.

**Comment by al-fisher** [comment]
Can confirm this is working for custom meshes stored in the `RenderMesh` Key 
image

**Review by al-fisher — CHANGES_REQUESTED** [review]
This is working as per comment. 👍 
@alelom - think you need to update a reference to `Graphics_oM` - at least I did need to get this to work.
Potentially as a result of combing through .csproj compliance.

**Comment by alelom** [comment]
> @alelom - think you need to update a reference to `Graphics_oM` - at least I did need to get this to work.
> Potentially as a result of combing through .csproj compliance.

@al-fisher Just for safety, I have removed and re-added all the `Graphics_oM` dll references in all three projects, but no change was detected by Git. I am not sure what you mean – it compiles and works fine on my machine.

**Comment by alelom** [comment]
> @alelom - think you need to update a reference to `Graphics_oM` - at least I did need to get this to work.

Thanks @al-fisher! Nevermind my (deleted) previous message - corrected now.

**Comment by alelom** [comment]
@al-fisher if happy it would be good to get this merged – need to branch out to remove the dependencies on Rhino.

**Review by al-fisher — APPROVED** [review]
As per comments above

**Pull request merged**
